//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.YMobile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cls_Account", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class cls_Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastBalance {
            get {
                return this.LastBalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.LastBalanceField, value) != true)) {
                    this.LastBalanceField = value;
                    this.RaisePropertyChanged("LastBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YMobile.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name MobileNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        WindowsFormsApp1.YMobile.GetAccountResponse GetAccount(WindowsFormsApp1.YMobile.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.GetAccountResponse> GetAccountAsync(WindowsFormsApp1.YMobile.GetAccountRequest request);
        
        // CODEGEN: Generating message contract since element name MobileNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/payment", ReplyAction="*")]
        WindowsFormsApp1.YMobile.paymentResponse payment(WindowsFormsApp1.YMobile.paymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/payment", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.paymentResponse> paymentAsync(WindowsFormsApp1.YMobile.paymentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.YMobile.GetAccountRequestBody Body;
        
        public GetAccountRequest() {
        }
        
        public GetAccountRequest(WindowsFormsApp1.YMobile.GetAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MobileNo;
        
        public GetAccountRequestBody() {
        }
        
        public GetAccountRequestBody(string MobileNo) {
            this.MobileNo = MobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.YMobile.GetAccountResponseBody Body;
        
        public GetAccountResponse() {
        }
        
        public GetAccountResponse(WindowsFormsApp1.YMobile.GetAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.YMobile.cls_Account GetAccountResult;
        
        public GetAccountResponseBody() {
        }
        
        public GetAccountResponseBody(WindowsFormsApp1.YMobile.cls_Account GetAccountResult) {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="payment", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.YMobile.paymentRequestBody Body;
        
        public paymentRequest() {
        }
        
        public paymentRequest(WindowsFormsApp1.YMobile.paymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pay;
        
        public paymentRequestBody() {
        }
        
        public paymentRequestBody(string MobileNo, string pay) {
            this.MobileNo = MobileNo;
            this.pay = pay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.YMobile.paymentResponseBody Body;
        
        public paymentResponse() {
        }
        
        public paymentResponse(WindowsFormsApp1.YMobile.paymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte paymentResult;
        
        public paymentResponseBody() {
        }
        
        public paymentResponseBody(byte paymentResult) {
            this.paymentResult = paymentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApp1.YMobile.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.YMobile.WebServiceSoap>, WindowsFormsApp1.YMobile.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.YMobile.GetAccountResponse WindowsFormsApp1.YMobile.WebServiceSoap.GetAccount(WindowsFormsApp1.YMobile.GetAccountRequest request) {
            return base.Channel.GetAccount(request);
        }
        
        public WindowsFormsApp1.YMobile.cls_Account GetAccount(string MobileNo) {
            WindowsFormsApp1.YMobile.GetAccountRequest inValue = new WindowsFormsApp1.YMobile.GetAccountRequest();
            inValue.Body = new WindowsFormsApp1.YMobile.GetAccountRequestBody();
            inValue.Body.MobileNo = MobileNo;
            WindowsFormsApp1.YMobile.GetAccountResponse retVal = ((WindowsFormsApp1.YMobile.WebServiceSoap)(this)).GetAccount(inValue);
            return retVal.Body.GetAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.GetAccountResponse> WindowsFormsApp1.YMobile.WebServiceSoap.GetAccountAsync(WindowsFormsApp1.YMobile.GetAccountRequest request) {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.GetAccountResponse> GetAccountAsync(string MobileNo) {
            WindowsFormsApp1.YMobile.GetAccountRequest inValue = new WindowsFormsApp1.YMobile.GetAccountRequest();
            inValue.Body = new WindowsFormsApp1.YMobile.GetAccountRequestBody();
            inValue.Body.MobileNo = MobileNo;
            return ((WindowsFormsApp1.YMobile.WebServiceSoap)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.YMobile.paymentResponse WindowsFormsApp1.YMobile.WebServiceSoap.payment(WindowsFormsApp1.YMobile.paymentRequest request) {
            return base.Channel.payment(request);
        }
        
        public byte payment(string MobileNo, string pay) {
            WindowsFormsApp1.YMobile.paymentRequest inValue = new WindowsFormsApp1.YMobile.paymentRequest();
            inValue.Body = new WindowsFormsApp1.YMobile.paymentRequestBody();
            inValue.Body.MobileNo = MobileNo;
            inValue.Body.pay = pay;
            WindowsFormsApp1.YMobile.paymentResponse retVal = ((WindowsFormsApp1.YMobile.WebServiceSoap)(this)).payment(inValue);
            return retVal.Body.paymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.paymentResponse> WindowsFormsApp1.YMobile.WebServiceSoap.paymentAsync(WindowsFormsApp1.YMobile.paymentRequest request) {
            return base.Channel.paymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.YMobile.paymentResponse> paymentAsync(string MobileNo, string pay) {
            WindowsFormsApp1.YMobile.paymentRequest inValue = new WindowsFormsApp1.YMobile.paymentRequest();
            inValue.Body = new WindowsFormsApp1.YMobile.paymentRequestBody();
            inValue.Body.MobileNo = MobileNo;
            inValue.Body.pay = pay;
            return ((WindowsFormsApp1.YMobile.WebServiceSoap)(this)).paymentAsync(inValue);
        }
    }
}
